repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: cargo-check
      - id: clippy
        args: ["--fix", "--allow-dirty"]

  - repo: https://github.com/ambv/black
    rev: 24.10.0
    hooks:
      - id: black
        name: black-24.10.0

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
