# Maximum width of a line
max_width = 100

# Following values are expressed in percentage relatively to `max_width`
fn_call_width = 75
attr_fn_like_width = 75
struct_lit_width = 75
struct_variant_width = 75
single_line_if_else_max_width = 80
single_line_let_else_max_width = 80
